modLoader="javafml" #mandatory
loaderVersion="[44,)" #mandatory
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/trikzon/ash/issues" #optional

[[mods]] #mandatory
modId="ash" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Ash" #mandatory
#updateJSONURL="" #optional
displayURL="https://github.com/trikzon/ash" #optional
logoFile="assets/ash/icon.png" #optional
#credits="" #optional
authors="Trikzon" #optional
description='''
An API that provides an abstraction layer between the three main Minecraft mod loaders (Fabric, Forge, and Quilt).
'''

[[dependencies.ash]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[44,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"

[[dependencies.ash]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
